### ISSUE TITLE
Passer can't interact with Extended Drawers

### ISSUE THREAD

**Issue by hatkidchan** [foxynotail/create-storage-mod-fabric#4] opened 2024-05-31 11:20 UTC
Self-explanatory, neither of passers can suck/push items from/to drawers from [Extended Drawers](https://modrinth.com/mod/extended-drawers) mod.

![2024-05-31_12 47 07](https://github.com/foxynotail/create-storage-mod-fabric/assets/35804000/215dd75a-4751-408c-a115-a0570227f605)
![2024-05-31_14 16 42](https://github.com/foxynotail/create-storage-mod-fabric/assets/35804000/f9211319-111f-48ae-a063-ba3b82b7ae99)
![2024-05-31_14 20 18](https://github.com/foxynotail/create-storage-mod-fabric/assets/35804000/28ea6f35-57d8-403e-a1cd-59df5d4b4ac9)

Count doesn't change over time in either direction.

**Comment by skippyall** [comment] 2024-06-13 20:07
The problem is that the Extended Drawers use the fabric storage api, but the passers only work with vanilla inventories. It would be better to use the fabric transfer api which works with both.

**Comment by foxynotail** [comment] 2024-06-28 17:26
This should be fixed now

**Closed by foxynotail** 2024-06-28 17:26 UTC
